import type {
  Profile,
  B2BClient,
  Account,
  InboxItem,
  LedgerEntry,
  ClientBalance,
  InboxSummary,
  BankTransaction,
  AuditEvent,
} from '@/types/database';
import type { SessionInfo, WhatsAppMessage } from '@/types/whatsapp';

export const DEMO_PROFILE: Profile = {
  id: 'demo-user-1',
  full_name: 'Andrés',
  role: 'superadmin',
  is_active: true,
  created_at: '2025-01-15T10:00:00Z',
  updated_at: '2025-01-15T10:00:00Z',
};

export const DEMO_CLIENTS: B2BClient[] = [
  {
    id: 'client-1',
    name: 'Mutual Rosario',
    business_name: 'Mutual de Ayuda Rosario SA',
    tax_id: '30-71234567-8',
    contact_email: 'admin@mutualrosario.com.ar',
    contact_phone: '+5493415551001',
    notes: 'Socio principal desde 2022',
    is_active: true,
    created_by: 'demo-user-1',
    created_at: '2025-01-20T10:00:00Z',
    updated_at: '2025-01-20T10:00:00Z',
  },
  {
    id: 'client-2',
    name: 'Cooperativa Sur',
    business_name: 'Cooperativa del Sur Ltda',
    tax_id: '30-72345678-9',
    contact_email: 'contacto@coopsur.com.ar',
    contact_phone: '+5493415552002',
    notes: null,
    is_active: true,
    created_by: 'demo-user-1',
    created_at: '2025-02-01T10:00:00Z',
    updated_at: '2025-02-01T10:00:00Z',
  },
  {
    id: 'client-3',
    name: 'Red Pagos Express',
    business_name: 'RPE SRL',
    tax_id: '30-73456789-0',
    contact_email: 'ops@rpexpress.com.ar',
    contact_phone: '+5493415553003',
    notes: 'Zona norte',
    is_active: true,
    created_by: 'demo-user-1',
    created_at: '2025-02-15T10:00:00Z',
    updated_at: '2025-02-15T10:00:00Z',
  },
  {
    id: 'client-4',
    name: 'Mutual Centro',
    business_name: 'Mutual del Centro SA',
    tax_id: '30-74567890-1',
    contact_email: null,
    contact_phone: '+5493415554004',
    notes: null,
    is_active: true,
    created_by: 'demo-user-1',
    created_at: '2025-03-01T10:00:00Z',
    updated_at: '2025-03-01T10:00:00Z',
  },
  {
    id: 'client-5',
    name: 'Servicios Norte',
    business_name: null,
    tax_id: '20-45678901-2',
    contact_email: 'info@servnorte.com.ar',
    contact_phone: null,
    notes: 'Pendiente contrato',
    is_active: false,
    created_by: 'demo-user-1',
    created_at: '2025-03-10T10:00:00Z',
    updated_at: '2025-03-10T10:00:00Z',
  },
];

export const DEMO_ACCOUNTS: Account[] = [
  {
    id: 'acc-1',
    name: 'Macro Pesos',
    account_type: 'banco',
    bank_name: 'Banco Macro',
    account_number: '3001-12345678-01',
    cbu: '2850590940090418135201',
    alias: 'RECAUDADORA.MACRO',
    notes: 'Cuenta principal',
    is_active: true,
    created_by: 'demo-user-1',
    created_at: '2025-01-10T10:00:00Z',
    updated_at: '2025-01-10T10:00:00Z',
  },
  {
    id: 'acc-2',
    name: 'Credicoop Pesos',
    account_type: 'banco',
    bank_name: 'Banco Credicoop',
    account_number: '191-12345678-01',
    cbu: '1910590940090418135202',
    alias: 'RECAUDADORA.COOP',
    notes: null,
    is_active: true,
    created_by: 'demo-user-1',
    created_at: '2025-01-10T10:00:00Z',
    updated_at: '2025-01-10T10:00:00Z',
  },
  {
    id: 'acc-3',
    name: 'MercadoPago',
    account_type: 'billetera',
    bank_name: null,
    account_number: null,
    cbu: null,
    alias: null,
    notes: 'Billetera virtual',
    is_active: true,
    created_by: 'demo-user-1',
    created_at: '2025-02-01T10:00:00Z',
    updated_at: '2025-02-01T10:00:00Z',
  },
  {
    id: 'acc-4',
    name: 'Proveedor Saldo',
    account_type: 'proveedor_saldo_virtual',
    bank_name: null,
    account_number: null,
    cbu: null,
    alias: null,
    notes: 'Saldo virtual con proveedor X',
    is_active: true,
    created_by: 'demo-user-1',
    created_at: '2025-02-15T10:00:00Z',
    updated_at: '2025-02-15T10:00:00Z',
  },
];

const now = new Date();
function hoursAgo(h: number) {
  return new Date(now.getTime() - h * 3600000).toISOString();
}
function daysAgo(d: number) {
  return new Date(now.getTime() - d * 86400000).toISOString();
}
function dateStr(d: number) {
  return new Date(now.getTime() - d * 86400000).toISOString().split('T')[0];
}

export const DEMO_INBOX: InboxItem[] = [
  {
    id: 'inb-001',
    source: 'whatsapp',
    status: 'aplicado',
    wa_message_id: 'wa-msg-001',
    wa_phone_number: '+5493415551001',
    wa_timestamp: daysAgo(2),
    client_id: 'client-1',
    account_id: 'acc-1',
    amount: 150000,
    transaction_date: dateStr(2),
    reference_number: 'TRF-44821',
    ocr_amount_confidence: 'alta',
    ocr_date_confidence: 'alta',
    ocr_reference_confidence: 'media',
    original_image_url: null,
    processed_image_url: null,
    notes: null,
    rejection_reason: null,
    assigned_to: null,
    processed_by: 'demo-user-1',
    processed_at: daysAgo(2),
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
    client: DEMO_CLIENTS[0],
    account: DEMO_ACCOUNTS[0],
  },
  {
    id: 'inb-002',
    source: 'whatsapp',
    status: 'verificado',
    wa_message_id: 'wa-msg-002',
    wa_phone_number: '+5493415552002',
    wa_timestamp: daysAgo(1),
    client_id: 'client-2',
    account_id: 'acc-2',
    amount: 87500,
    transaction_date: dateStr(1),
    reference_number: 'DEP-99012',
    ocr_amount_confidence: 'alta',
    ocr_date_confidence: 'media',
    ocr_reference_confidence: 'alta',
    original_image_url: null,
    processed_image_url: null,
    notes: null,
    rejection_reason: null,
    assigned_to: null,
    processed_by: 'demo-user-1',
    processed_at: daysAgo(1),
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
    client: DEMO_CLIENTS[1],
    account: DEMO_ACCOUNTS[1],
  },
  {
    id: 'inb-003',
    source: 'whatsapp',
    status: 'pendiente_verificacion',
    wa_message_id: 'wa-msg-003',
    wa_phone_number: '+5493415553003',
    wa_timestamp: hoursAgo(5),
    client_id: 'client-3',
    account_id: 'acc-1',
    amount: 220000,
    transaction_date: dateStr(0),
    reference_number: 'TRF-44900',
    ocr_amount_confidence: 'alta',
    ocr_date_confidence: 'alta',
    ocr_reference_confidence: 'baja',
    original_image_url: null,
    processed_image_url: null,
    notes: null,
    rejection_reason: null,
    assigned_to: null,
    processed_by: null,
    processed_at: null,
    created_at: hoursAgo(5),
    updated_at: hoursAgo(5),
    client: DEMO_CLIENTS[2],
    account: DEMO_ACCOUNTS[0],
  },
  {
    id: 'inb-004',
    source: 'whatsapp',
    status: 'pendiente_verificacion',
    wa_message_id: 'wa-msg-004',
    wa_phone_number: '+5493415551001',
    wa_timestamp: hoursAgo(3),
    client_id: 'client-1',
    account_id: 'acc-3',
    amount: 45000,
    transaction_date: dateStr(0),
    reference_number: null,
    ocr_amount_confidence: 'media',
    ocr_date_confidence: 'media',
    ocr_reference_confidence: null,
    original_image_url: null,
    processed_image_url: null,
    notes: 'Foto borrosa',
    rejection_reason: null,
    assigned_to: null,
    processed_by: null,
    processed_at: null,
    created_at: hoursAgo(3),
    updated_at: hoursAgo(3),
    client: DEMO_CLIENTS[0],
    account: DEMO_ACCOUNTS[2],
  },
  {
    id: 'inb-005',
    source: 'whatsapp',
    status: 'recibido',
    wa_message_id: 'wa-msg-005',
    wa_phone_number: '+5493415554004',
    wa_timestamp: hoursAgo(1),
    client_id: 'client-4',
    account_id: null,
    amount: null,
    transaction_date: null,
    reference_number: null,
    ocr_amount_confidence: null,
    ocr_date_confidence: null,
    ocr_reference_confidence: null,
    original_image_url: null,
    processed_image_url: null,
    notes: null,
    rejection_reason: null,
    assigned_to: null,
    processed_by: null,
    processed_at: null,
    created_at: hoursAgo(1),
    updated_at: hoursAgo(1),
    client: DEMO_CLIENTS[3],
    account: undefined,
  },
  {
    id: 'inb-006',
    source: 'upload_manual',
    status: 'ocr_listo',
    wa_message_id: null,
    wa_phone_number: null,
    wa_timestamp: null,
    client_id: 'client-2',
    account_id: 'acc-2',
    amount: 310000,
    transaction_date: dateStr(0),
    reference_number: 'DEP-99100',
    ocr_amount_confidence: 'alta',
    ocr_date_confidence: 'alta',
    ocr_reference_confidence: 'alta',
    original_image_url: null,
    processed_image_url: null,
    notes: null,
    rejection_reason: null,
    assigned_to: null,
    processed_by: null,
    processed_at: null,
    created_at: hoursAgo(2),
    updated_at: hoursAgo(2),
    client: DEMO_CLIENTS[1],
    account: DEMO_ACCOUNTS[1],
  },
  {
    id: 'inb-007',
    source: 'whatsapp',
    status: 'rechazado',
    wa_message_id: 'wa-msg-007',
    wa_phone_number: '+5493415559999',
    wa_timestamp: daysAgo(3),
    client_id: null,
    account_id: null,
    amount: 5000,
    transaction_date: dateStr(3),
    reference_number: null,
    ocr_amount_confidence: 'baja',
    ocr_date_confidence: 'baja',
    ocr_reference_confidence: null,
    original_image_url: null,
    processed_image_url: null,
    notes: null,
    rejection_reason: 'Teléfono desconocido, imagen ilegible',
    assigned_to: null,
    processed_by: 'demo-user-1',
    processed_at: daysAgo(3),
    created_at: daysAgo(3),
    updated_at: daysAgo(3),
  },
  {
    id: 'inb-008',
    source: 'whatsapp',
    status: 'recibido',
    wa_message_id: 'wa-msg-008',
    wa_phone_number: '+5493415551001',
    wa_timestamp: hoursAgo(0.5),
    client_id: 'client-1',
    account_id: null,
    amount: null,
    transaction_date: null,
    reference_number: null,
    ocr_amount_confidence: null,
    ocr_date_confidence: null,
    ocr_reference_confidence: null,
    original_image_url: null,
    processed_image_url: null,
    notes: null,
    rejection_reason: null,
    assigned_to: null,
    processed_by: null,
    processed_at: null,
    created_at: hoursAgo(0.5),
    updated_at: hoursAgo(0.5),
    client: DEMO_CLIENTS[0],
    account: undefined,
  },
];

export const DEMO_CLIENT_BALANCES: ClientBalance[] = [
  { client_id: 'client-1', client_name: 'Mutual Rosario', total_credito: 650000, total_debito: 480000, saldo: 170000 },
  { client_id: 'client-2', client_name: 'Cooperativa Sur', total_credito: 397500, total_debito: 350000, saldo: 47500 },
  { client_id: 'client-3', client_name: 'Red Pagos Express', total_credito: 220000, total_debito: 0, saldo: 220000 },
  { client_id: 'client-4', client_name: 'Mutual Centro', total_credito: 85000, total_debito: 90000, saldo: -5000 },
];

export const DEMO_INBOX_SUMMARY: InboxSummary[] = [
  { status: 'recibido', count: 2, total_amount: 0 },
  { status: 'ocr_listo', count: 1, total_amount: 310000 },
  { status: 'pendiente_verificacion', count: 2, total_amount: 265000 },
  { status: 'verificado', count: 1, total_amount: 87500 },
  { status: 'aplicado', count: 1, total_amount: 150000 },
  { status: 'rechazado', count: 1, total_amount: 5000 },
];

export const DEMO_LEDGER: LedgerEntry[] = [
  {
    id: 'led-1', client_id: 'client-1', entry_type: 'credito', category: 'deposito_verificado',
    amount: 150000, description: 'Depósito verificado TRF-44821',
    inbox_item_id: 'inb-001', reconciliation_id: null, reversal_of: null,
    created_by: 'demo-user-1', reason: null, created_at: daysAgo(2),
    client: DEMO_CLIENTS[0] as B2BClient, creator: DEMO_PROFILE,
  },
  {
    id: 'led-2', client_id: 'client-1', entry_type: 'debito', category: 'entrega',
    amount: 120000, description: 'Entrega efectivo — sucursal Centro',
    inbox_item_id: null, reconciliation_id: null, reversal_of: null,
    created_by: 'demo-user-1', reason: null, created_at: daysAgo(1),
    client: DEMO_CLIENTS[0], creator: DEMO_PROFILE,
  },
  {
    id: 'led-3', client_id: 'client-2', entry_type: 'credito', category: 'deposito_verificado',
    amount: 87500, description: 'Depósito verificado DEP-99012',
    inbox_item_id: 'inb-002', reconciliation_id: null, reversal_of: null,
    created_by: 'demo-user-1', reason: null, created_at: daysAgo(1),
    client: DEMO_CLIENTS[1], creator: DEMO_PROFILE,
  },
  {
    id: 'led-4', client_id: 'client-1', entry_type: 'debito', category: 'comision',
    amount: 7500, description: 'Comisión febrero 2026',
    inbox_item_id: null, reconciliation_id: null, reversal_of: null,
    created_by: 'demo-user-1', reason: 'Comisión mensual', created_at: daysAgo(1),
    client: DEMO_CLIENTS[0], creator: DEMO_PROFILE,
  },
  {
    id: 'led-5', client_id: 'client-3', entry_type: 'credito', category: 'deposito_verificado',
    amount: 220000, description: 'Depósito pendiente — TRF-44900',
    inbox_item_id: 'inb-003', reconciliation_id: null, reversal_of: null,
    created_by: 'demo-user-1', reason: null, created_at: hoursAgo(4),
    client: DEMO_CLIENTS[2], creator: DEMO_PROFILE,
  },
  {
    id: 'led-6', client_id: 'client-2', entry_type: 'debito', category: 'entrega',
    amount: 50000, description: 'Entrega parcial — zona sur',
    inbox_item_id: null, reconciliation_id: null, reversal_of: null,
    created_by: 'demo-user-1', reason: null, created_at: hoursAgo(2),
    client: DEMO_CLIENTS[1], creator: DEMO_PROFILE,
  },
];

export const DEMO_BANK_TRANSACTIONS: BankTransaction[] = [
  {
    id: 'btx-1', account_id: 'acc-1', import_id: null,
    transaction_date: dateStr(2), amount: 150000, is_credit: true,
    reference: 'TRF-44821', description: 'TRANSFERENCIA RECIBIDA',
    external_id: 'macro-001', is_reconciled: true, source: 'import',
    created_by: 'demo-user-1', created_at: daysAgo(2),
    account: DEMO_ACCOUNTS[0],
  },
  {
    id: 'btx-2', account_id: 'acc-2', import_id: null,
    transaction_date: dateStr(1), amount: 87500, is_credit: true,
    reference: 'DEP-99012', description: 'DEPOSITO EN EFECTIVO',
    external_id: 'coop-001', is_reconciled: true, source: 'import',
    created_by: 'demo-user-1', created_at: daysAgo(1),
    account: DEMO_ACCOUNTS[1],
  },
  {
    id: 'btx-3', account_id: 'acc-1', import_id: null,
    transaction_date: dateStr(0), amount: 220000, is_credit: true,
    reference: 'TRF-44900', description: 'TRANSFERENCIA RECIBIDA',
    external_id: 'macro-002', is_reconciled: false, source: 'import',
    created_by: 'demo-user-1', created_at: hoursAgo(4),
    account: DEMO_ACCOUNTS[0],
  },
  {
    id: 'btx-4', account_id: 'acc-1', import_id: null,
    transaction_date: dateStr(0), amount: 75000, is_credit: true,
    reference: 'TRF-44910', description: 'TRANSFERENCIA RECIBIDA',
    external_id: 'macro-003', is_reconciled: false, source: 'import',
    created_by: 'demo-user-1', created_at: hoursAgo(2),
    account: DEMO_ACCOUNTS[0],
  },
];

export const DEMO_AUDIT: AuditEvent[] = [
  {
    id: 'aud-1', user_id: 'demo-user-1', action: 'inbox_item_verified',
    entity_type: 'inbox_items', entity_id: 'inb-001',
    before_data: { status: 'pendiente_verificacion' },
    after_data: { status: 'verificado' }, metadata: {},
    ip_address: null, created_at: daysAgo(2),
  },
  {
    id: 'aud-2', user_id: 'demo-user-1', action: 'ledger_entry_created',
    entity_type: 'ledger_entries', entity_id: 'led-1',
    before_data: null,
    after_data: { client_id: 'client-1', amount: 150000 }, metadata: {},
    ip_address: null, created_at: daysAgo(2),
  },
  {
    id: 'aud-3', user_id: 'demo-user-1', action: 'reconciliation_confirmed',
    entity_type: 'reconciliations', entity_id: 'rec-1',
    before_data: null,
    after_data: { inbox_item_id: 'inb-001', bank_transaction_id: 'btx-1' }, metadata: {},
    ip_address: null, created_at: daysAgo(2),
  },
  {
    id: 'aud-4', user_id: 'demo-user-1', action: 'client_created',
    entity_type: 'b2b_clients', entity_id: 'client-3',
    before_data: null,
    after_data: { name: 'Red Pagos Express' }, metadata: {},
    ip_address: null, created_at: daysAgo(5),
  },
  {
    id: 'aud-5', user_id: 'demo-user-1', action: 'ledger_entry_created',
    entity_type: 'ledger_entries', entity_id: 'led-4',
    before_data: null,
    after_data: { client_id: 'client-1', category: 'comision', amount: 7500 }, metadata: {},
    ip_address: null, created_at: daysAgo(1),
  },
];

// ============================================================
// WhatsApp Baileys Demo Data
// ============================================================

export const DEMO_WA_SESSIONS: SessionInfo[] = [
  {
    id: 'andres-principal',
    status: 'connected',
    phoneNumber: '5493415550001',
    name: 'Andres Recaudadora',
    qrDataUrl: null,
    createdAt: '2026-02-20T10:00:00Z',
    lastMessageAt: hoursAgo(0.5),
    messageCount: 142,
  },
  {
    id: 'oficina-norte',
    status: 'connected',
    phoneNumber: '5493415550002',
    name: 'Oficina Norte',
    qrDataUrl: null,
    createdAt: '2026-02-25T14:00:00Z',
    lastMessageAt: hoursAgo(2),
    messageCount: 67,
  },
  {
    id: 'sucursal-sur',
    status: 'disconnected',
    phoneNumber: '5493415550003',
    name: 'Sucursal Sur',
    qrDataUrl: null,
    createdAt: '2026-02-28T09:00:00Z',
    lastMessageAt: daysAgo(1),
    messageCount: 23,
  },
];

export const DEMO_WA_MESSAGES: WhatsAppMessage[] = [
  {
    id: 'wam-001',
    sessionId: 'andres-principal',
    remoteJid: '5493415551001@s.whatsapp.net',
    phoneNumber: '5493415551001',
    pushName: 'Carlos - Mutual Rosario',
    fromMe: false,
    messageType: 'image',
    textContent: 'Buen dia, te mando el comprobante de la transferencia de hoy',
    mediaUrl: null,
    mimeType: 'image/jpeg',
    timestamp: Math.floor(new Date(hoursAgo(0.5)).getTime() / 1000),
    createdAt: hoursAgo(0.5),
  },
  {
    id: 'wam-002',
    sessionId: 'andres-principal',
    remoteJid: '5493415552002@s.whatsapp.net',
    phoneNumber: '5493415552002',
    pushName: 'Maria - Coop Sur',
    fromMe: false,
    messageType: 'text',
    textContent: 'Hola Andres, ya hicimos el deposito de $87.500 en Credicoop. Te paso el comprobante en un rato',
    mediaUrl: null,
    mimeType: null,
    timestamp: Math.floor(new Date(hoursAgo(1)).getTime() / 1000),
    createdAt: hoursAgo(1),
  },
  {
    id: 'wam-003',
    sessionId: 'andres-principal',
    remoteJid: '5493415553003@s.whatsapp.net',
    phoneNumber: '5493415553003',
    pushName: 'Juan RPE',
    fromMe: false,
    messageType: 'image',
    textContent: 'Transferencia realizada $220.000',
    mediaUrl: null,
    mimeType: 'image/jpeg',
    timestamp: Math.floor(new Date(hoursAgo(2)).getTime() / 1000),
    createdAt: hoursAgo(2),
  },
  {
    id: 'wam-004',
    sessionId: 'oficina-norte',
    remoteJid: '5493415554004@s.whatsapp.net',
    phoneNumber: '5493415554004',
    pushName: 'Pedro Mutual Centro',
    fromMe: false,
    messageType: 'document',
    textContent: 'comprobante_febrero.pdf',
    mediaUrl: null,
    mimeType: 'application/pdf',
    timestamp: Math.floor(new Date(hoursAgo(3)).getTime() / 1000),
    createdAt: hoursAgo(3),
  },
  {
    id: 'wam-005',
    sessionId: 'andres-principal',
    remoteJid: '5493415551001@s.whatsapp.net',
    phoneNumber: '5493415551001',
    pushName: 'Carlos - Mutual Rosario',
    fromMe: false,
    messageType: 'text',
    textContent: 'Ahi te mande la foto del comprobante, fijate si llego bien',
    mediaUrl: null,
    mimeType: null,
    timestamp: Math.floor(new Date(hoursAgo(0.5)).getTime() / 1000),
    createdAt: hoursAgo(0.5),
  },
  {
    id: 'wam-006',
    sessionId: 'andres-principal',
    remoteJid: '5493415551001@s.whatsapp.net',
    phoneNumber: '5493415551001',
    pushName: 'Carlos - Mutual Rosario',
    fromMe: true,
    messageType: 'text',
    textContent: 'Recibido, gracias Carlos!',
    mediaUrl: null,
    mimeType: null,
    timestamp: Math.floor(new Date(hoursAgo(0.4)).getTime() / 1000),
    createdAt: hoursAgo(0.4),
  },
  {
    id: 'wam-007',
    sessionId: 'oficina-norte',
    remoteJid: '5493415559876@s.whatsapp.net',
    phoneNumber: '5493415559876',
    pushName: 'Laura',
    fromMe: false,
    messageType: 'image',
    textContent: null,
    mediaUrl: null,
    mimeType: 'image/png',
    timestamp: Math.floor(new Date(hoursAgo(5)).getTime() / 1000),
    createdAt: hoursAgo(5),
  },
  {
    id: 'wam-008',
    sessionId: 'andres-principal',
    remoteJid: '5493415558888@s.whatsapp.net',
    phoneNumber: '5493415558888',
    pushName: null,
    fromMe: false,
    messageType: 'audio',
    textContent: null,
    mediaUrl: null,
    mimeType: 'audio/ogg',
    timestamp: Math.floor(new Date(hoursAgo(8)).getTime() / 1000),
    createdAt: hoursAgo(8),
  },
];
